# Required since ceph-helm does not provide bootstrap.keyring.mgr but
# ceph-mgr-keyring-generator requires it at runtime.
# Requires ceph-helm templates to be disabled:
#   manifests.configmap_templates=false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-templates
data:
  admin.keyring: |+
    [client.admin]
      key = {{"{{"}} key {{"}}"}}
      auid = 0
      caps mds = "allow"
      caps mon = "allow *"
      caps osd = "allow *"
      caps mgr = "allow *"
    
  bootstrap.keyring.mds: |+
    [client.bootstrap-mds]
      key = {{"{{"}} key {{"}}"}}
      caps mon = "allow profile bootstrap-mds"
    
  bootstrap.keyring.osd: |+
    [client.bootstrap-osd]
      key = {{"{{"}} key {{"}}"}}
      caps mon = "allow profile bootstrap-osd"
    
  bootstrap.keyring.rgw: |+
    [client.bootstrap-rgw]
      key = {{"{{"}} key {{"}}"}}
      caps mon = "allow profile bootstrap-rgw"
    
  bootstrap.keyring.mgr: |+
    [client.bootstrap-mgr]
      key = {{"{{"}} key {{"}}"}}
      caps mon = "allow profile bootstrap-mgr"
    
  mon.keyring: |+
    [mon.]
      key = {{"{{"}} key {{"}}"}}
      caps mon = "allow *"
