#FROM golang:1.10-alpine AS cfssl
#RUN apk add --update --no-cache git build-base
#RUN git clone https://github.com/cloudflare/cfssl.git $GOPATH/src/github.com/cloudflare/cfssl --branch 1.3.2
#RUN go get github.com/cloudflare/cfssl_trust/... \
#	&& cp -R /go/src/github.com/cloudflare/cfssl_trust /etc/cfssl
#WORKDIR /go/src/github.com/cloudflare/cfssl
#RUN CGO_ENABLED=0 GOOS=linux go install -a -ldflags '-extldflags "-static"' ./cmd/...


# Build CRI-O
#FROM saschagrunert/crionix:1.0.0 AS crio
FROM golang:1.12-alpine3.10 AS crio
RUN apk add --update --no-cache git make gcc pkgconf musl-dev \
	btrfs-progs btrfs-progs-dev libassuan-dev lvm2-dev device-mapper \
	glib-static libc-dev gpgme-dev protobuf-dev protobuf-c-dev \
	libseccomp-dev libselinux-dev ostree-dev openssl iptables bash \
	go-md2man
ARG CRIO_VERSION=v1.16.0
RUN git clone --branch=$CRIO_VERSION https://github.com/cri-o/cri-o /go/src/github.com/cri-o/cri-o
WORKDIR /go/src/github.com/cri-o/cri-o
#RUN nix-build cri-o/nix --argstr revision ${CRIO_VERSION}
RUN set -ex; \
    make bin/crio SHRINKFLAGS='-s -w -extldflags "-static"' BUILDTAGS='seccomp selinux varlink exclude_graphdriver_devicemapper containers_image_ostree_stub containers_image_openpgp'; \
	bin/crio --help >/dev/null; \
	[ "$(ldd bin/crio | wc -l)" -eq 0 ] || (ldd bin/crio; false)


FROM mgoltzsche/podman:1.6.2 AS podman


FROM centos:7

# Install systemd
ENV container docker
RUN yum -y update && yum -y install systemd && yum clean all \
	&& (cd /lib/systemd/system/sysinit.target.wants/ && for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done) \
	&& rm -f /lib/systemd/system/multi-user.target.wants/* \
	&& rm -f /etc/systemd/system/*.wants/* \
	&& rm -f /lib/systemd/system/local-fs.target.wants/* \
	&& rm -f /lib/systemd/system/sockets.target.wants/*udev* \
	&& rm -f /lib/systemd/system/sockets.target.wants/*initctl* \
	&& rm -f /lib/systemd/system/basic.target.wants/* \
	&& rm -f /lib/systemd/system/anaconda.target.wants/* \
	&& rm -f /usr/lib/systemd/system/*.wants/systemd-update-utmp-runlevel.service
VOLUME [ "/sys/fs/cgroup" ]

RUN yum -y install iproute ebtables ethtool socat openssl xfsprogs e4fsprogs && yum clean all

# Install CNI plugins
ARG CNI_PLUGIN_VERSION=v0.8.2
RUN mkdir -p /opt/cni/bin \
	&& curl -L "https://github.com/containernetworking/plugins/releases/download/${CNI_PLUGIN_VERSION}/cni-plugins-linux-amd64-${CNI_PLUGIN_VERSION}.tgz" | tar -C /opt/cni/bin -xz

# Install crictl (required for kubeadm / Kubelet Container Runtime Interface (CRI))
ARG CRICTL_VERSION=v1.16.1
RUN mkdir -p /opt/bin \
	&& curl -L "https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz" | tar -C /opt/bin -xz

# Install kubeadm, kubelet, kubectl
# (for latest stable version see https://storage.googleapis.com/kubernetes-release/release/stable.txt)
ARG K8S_VERSION=v1.16.3
ENV K8S_VERSION=$K8S_VERSION
RUN mkdir -p /opt/bin \
	&& cd /opt/bin \
	&& curl -L --remote-name-all https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/{kubeadm,kubelet,kubectl} \
	&& chmod +x kubeadm kubelet kubectl \
	&& mkdir -p /etc/kubernetes/manifests

# Install CRI-O & podman
COPY --from=crio /go/src/github.com/cri-o/cri-o/bin/crio /usr/local/bin/crio
COPY --from=crio /go/src/github.com/cri-o/cri-o/contrib/sysconfig/crio /etc/sysconfig/crio
COPY --from=podman /usr/local/bin/runc /usr/local/bin/podman /usr/local/bin/
COPY --from=podman /usr/libexec/podman/conmon /usr/libexec/podman/conmon
#COPY --from=podman /usr/libexec/cni/loopback /usr/libexec/cni/flannel /usr/libexec/cni/bridge /usr/libexec/cni/portmap /opt/cni/bin/
COPY --from=podman /etc/containers /etc/containers
RUN set -ex; \
	mkdir /etc/crio /var/lib/crio; \
	crio --config="" config > /etc/crio/crio.conf; \
	ln -s /usr/libexec/podman/conmon /usr/local/bin/conmon
RUN set -ex; crio --help >/dev/null; runc --help >/dev/null; podman --help >/dev/null
COPY conf/sysctl.d /etc/sysctl.d
VOLUME ["/var/lib/containers"]

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
ENV KUBE_TYPE=master

#COPY conf/net /etc/cni/net.d

# Enable systemd services
COPY start-kubelet.sh /opt/bin/start-kubelet
COPY conf/systemd/* /etc/systemd/system/
RUN systemctl enable kubelet kubeadm crio crio-wipe crio-shutdown

# Make init script appear as systemd init process to support OCI hooks oci-systemd-hook and oci-register-machine
RUN mv /usr/sbin/init /usr/sbin/systemd
COPY entrypoint.sh /usr/sbin/init
COPY setup.sh /setup.sh

STOPSIGNAL 2
CMD ["/usr/sbin/init"]
