resources:
# ingress-nginx with LoadBalancer Service (requires metallb)
#- github.com/kubernetes/ingress-nginx//deploy/static/provider/cloud?ref=controller-v0.46.0
# ingress-nginx with NodePort Service (requires high port or kube-apiserver configured with a custom service-node-port-range)
- github.com/kubernetes/ingress-nginx//deploy/static/provider/baremetal?ref=controller-v0.46.0
patchesStrategicMerge:
- nodeport-service.yaml
