apiVersion: v1 # see https://metallb.universe.tf/configuration/
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.23.0.250-10.23.0.253
