ceph:
  images:
    ks_user: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
    ks_service: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
    ks_endpoints: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
    dep_check: docker.io/kolla/ubuntu-source-kubernetes-entrypoint:4.0.0
    bootstrap: docker.io/ceph/daemon:tag-build-master-luminous-ubuntu-16.04
    daemon: docker.io/ceph/daemon:tag-build-master-luminous-ubuntu-16.04
    ceph_config_helper: docker.io/port/ceph-config-helper:v1.10.3
    rbd_provisioner: quay.io/external_storage/rbd-provisioner:v2.1.1-k8s1.11
    minimal: docker.io/alpine:latest
    pull_policy: "IfNotPresent"
  
  bootstrap:
    enabled: true
    script: |
      ceph -s
      function ensure_pool () {
        ceph osd pool stats $1 || ceph osd pool create $1 $2
      }
      ensure_pool kube 8
  
  manifests:
    configmap_templates: false
    deployment_rbd_provisioner: false
  
  network:
    public: 10.23.0.0/12
    cluster: 10.23.0.0/12
  
  osd_directory:
    enabled: true
  conf:
    ceph:
      config:
        osd:
          # Required on ext4
          osd_max_object_name_len: 256
          osd_max_object_namespace_len: 64
  
  storageclass:
    name: ceph-rbd
    pool: kube
    # TODO: change or create user:
    user_id: k8s
  
  ceph_mgr_enabled_modules:
    - restful
    - status
    - dashboard
  
  ceph_mgr_modules_config:
    dashboard:
      port: 7000
    localpool:
      failure_domain: host
      subtree: rack
      pg_num: "128"
      num_rep: "3"
      min_size: "2"

  pod:
    dns_policy: "ClusterFirstWithHostNet"
    replicas:
      rgw: 1
      mon_check: 1
      rbd_provisioner: 1
      mgr: 1
    affinity:
        anti:
          type:
            default: preferredDuringSchedulingIgnoredDuringExecution
          topologyKey:
            default: kubernetes.io/hostname
    resources:
      enabled: false
      osd:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1024Mi"
          cpu: "1000m"
      mds:
        requests:
          memory: "10Mi"
          cpu: "250m"
        limits:
          memory: "50Mi"
          cpu: "500m"
      mon:
        requests:
          memory: "50Mi"
          cpu: "250m"
        limits:
          memory: "100Mi"
          cpu: "500m"
      mon_check:
        requests:
          memory: "5Mi"
          cpu: "250m"
        limits:
          memory: "50Mi"
          cpu: "500m"
      rgw:
        requests:
          memory: "5Mi"
          cpu: "250m"
        limits:
          memory: "50Mi"
          cpu: "500m"
      rbd_provisioner:
        requests:
          memory: "5Mi"
          cpu: "250m"
        limits:
          memory: "50Mi"
          cpu: "500m"
      mgr:
        requests:
          memory: "5Mi"
          cpu: "250m"
        limits:
          memory: "50Mi"
          cpu: "500m"
      jobs:
        bootstrap:
          limits:
            memory: "1024Mi"
            cpu: "2000m"
          requests:
            memory: "128Mi"
            cpu: "500m"
        secret_provisioning:
          limits:
            memory: "1024Mi"
            cpu: "2000m"
          requests:
            memory: "128Mi"
            cpu: "500m"
        ks_endpoints:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "2000m"
        ks_service:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "2000m"
        ks_user:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "2000m"

  secrets:
    keyrings:
      mon: ceph-mon-keyring
      mds: ceph-bootstrap-mds-keyring
      osd: ceph-bootstrap-osd-keyring
      rgw: ceph-bootstrap-rgw-keyring
      mgr: ceph-bootstrap-mgr-keyring
      admin: ceph-client-admin-keyring
