bases:
- deploy/cloud-generic
- deploy/cluster-wide

namespace: ingress-nginx

resources:
- namespace.yaml

patchesStrategicMerge:
- service-loadbalancer.yaml

images:
- name: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
  newName: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
  # 0.25.1 may result in https://github.com/kubernetes/ingress-nginx/issues/4311
  newTag: 0.24.1
