# See https://github.com/rook/rook/blob/master/Documentation/ceph-filesystem.md
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: shared
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - replicated:
        size: 3
  metadataServer:
    activeCount: 1
    activeStandby: true
