elastic-stack:
  elasticsearch:
    master:
      replicas: 2 # 3
      persistence:
        storageClass: rook-ceph-block
        size: '200Mi' # 4Gi
    data:
      persistence:
        storageClass: rook-ceph-block
        size: '500Mi' # 30 Gi
  kibana:
    env:
      # env var somehow ignored
      ELASTICSEARCH_URL: http://efk-elasticsearch-client:9200
    files:
      kibana.yml:
        server.name: kibana
        server.host: "0"
        elasticsearch.url: http://efk-elasticsearch-client:9200
    ingress:
      enabled: true
      hosts:
        - kibana.algorythm.de
      annotations:
        certmanager.k8s.io/cluster-issuer: cluster-ca-issuer
      tls:
        - secretName: algorythm-kibana-tls
          hosts:
            - kibana.algorythm.de
  fluent-bit:
    backend:
      type: es
      es:
        host: efk-elasticsearch-client
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 8Mi

logstash:
  enabled: false
fluentd:
  enabled: false
fluent-bit:
  enabled: true
elasticsearch-curator:
  enabled: true
elasticsearch-exporter:
  enabled: true
